# SPDX-FileCopyrightText: 2026 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Go lint

on: pull_request

permissions:
  contents: read

concurrency:
  group: go-lint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    name: golangci-lint
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Install CGO dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq libopus-dev

          VOSK_VERSION=0.3.45
          wget -q "https://github.com/alphacep/vosk-api/releases/download/v${VOSK_VERSION}/vosk-linux-x86_64-${VOSK_VERSION}.zip"
          unzip -q "vosk-linux-x86_64-${VOSK_VERSION}.zip"
          sudo cp "vosk-linux-x86_64-${VOSK_VERSION}/libvosk.so" /usr/local/lib/
          sudo cp "vosk-linux-x86_64-${VOSK_VERSION}/vosk_api.h" /usr/local/include/
          sudo ldconfig

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v6.5.0
        with:
          version: v2.1
